defmodule AshPop.Repo.Migrations.CreateLineItems do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:line_items, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :total_amt, :decimal
      add :tax_amt, :decimal
      add :subtotal_amt, :decimal
      add :qty, :decimal
      add :unit_price, :decimal
      add :id, :uuid, null: false, primary_key: true
    end
  end

  def down do
    drop table(:line_items)
  end
end
